site_name: OSG Management Area
site_url: https://osg-htc.org/management/
repo_url: https://github.com/osg-htc/management/
theme:
  name: material
  custom_dir: osgthedocs
  favicon: img/favicon.ico

nav:
  - Home: 'index.md'
  - Staff Meeting: staff-meeting.md
  - Area Coordinators: 'area-coordinators.md'
  - AC Meeting Archive: 'ac-meeting-archive.md'
  - Policies: 'policies.md'
  - Code of Conduct:    conduct.md

markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - footnotes
